version: '3.3'
services:

  replace-backend:
    image: localhost/replace-backend:latest
    environment:
      - "REPLACE.DATABASE.URL=jdbc:postgresql://localhost:5432/replace-app"
      - "REPLACE.DATABASE.USER=postgres"
      - "REPLACE.DATABASE.PASSWORD=postgres"
    ports:
      - "8002:80"
    network_mode: "host"
    labels:
      - "traefik.http.routers.api.rule=(Host(`app.localhost`) && PathPrefix(`/api`))"

  replace-frontend:
    build: web
    ports:
      - "8001:80"
    labels:
      - "traefik.http.routers.site.rule=Host(`app.localhost`)"

  proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "7000:80"
      - "8080:8080"
