version: '3.3'
services:
  proxy:
    image: traefik:latest
    command:
#      - "--accesslog"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:7000"
    ports:
      - "7000:7000"
      - "8080:8080"

  replace-backend:
    image: localhost/replace-backend:latest
    environment:
      - "REPLACE.DATABASE.URL=jdbc:postgresql://localhost:5432/replace-app"
      - "REPLACE.DATABASE.USER=postgres"
      - "REPLACE.DATABASE.PASSWORD=postgres"
    ports:
      - "8002:80"
    network_mode: "host"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"

  replace-frontend:
    build: web
    ports:
      - "8001:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
