version: '3.8'
services:
  db:
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: replace-app
    expose:
      - 5432
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"

  replace-backend:
    image: replace-backend:latest
    environment:
      - "REPLACE.DATABASE.URL=jdbc:postgresql://db:5432/replace-app"
      - "REPLACE.DATABASE.USER=postgres"
      - "REPLACE.DATABASE.PASSWORD=postgres"
      - "REPLACE.OAUTH.CALLBACK=http://localhost:8000/api/session/callback"
      - "REPLACE.OAUTH.CLIENT_ID=..."
      - "REPLACE.OAUTH.CLIENT_SECRET..."
    expose:
      - 80
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    depends_on:
      - db

  replace-frontend:
    build: web
    expose:
      - 80
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  proxy:
    image: traefik:latest
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
#      - "8080:8080" // Uncomment this line to access the Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - replace-backend
      - replace-frontend
