version: '3.3'
services:
  replace-frontend:
    build: web
    ports:
      - "4200:80"
#  replace-backend:
#    image: localhost/replace-backend:latest
#    environment:
#      - "REPLACE.DATABASE.URL=jdbc:postgresql://localhost:5432/replace-app"
#      - "REPLACE.DATABASE.USER=postgres"
#      - "REPLACE.DATABASE.PASSWORD=postgres"
#    ports:
#      - "8000:8000"
#    network_mode: "host"
#  proxy:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./web/src/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./web/src/nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - replace-frontend
#      - replace-backend
networks:
  default:
    driver: bridge
