version: '0.0'
services:
  replace-frontend:
    build: ./web/src/angular/
    ports:
      - 4200:80
    depends_on:
      - replace-backend
  replace-backend:
    build: ./
    ports:
      - 8000:8000
