version: '3.8'
services:
  replace-backend:
    image: ${REPLACE_ECR_BACKEND}:latest
    environment:
      - "REPLACE_DATABASE_URL=${REPLACE_DATABASE_URL}"
      - "REPLACE_DATABASE_USER=${REPLACE_DATABASE_USR}"
      - "REPLACE_DATABASE_PASSWORD=${REPLACE_DATABASE_PSW}"
      - "REPLACE_OAUTH_CALLBACK=http://localhost/api/session/callback"
      - "REPLACE_OAUTH_CLIENT_ID=${REPLACE_OAUTH_CLIENTID}"
      - "REPLACE_OAUTH_CLIENT_SECRET=${REPLACE_OAUTH_SECRET}"
    expose:
      - 8085
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"

  replace-frontend:
    image: ${REPLACE_ECR_FRONTEND}:latest
    expose:
      - 8085
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  proxy:
    image: traefik:latest
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=false"
      - "--providers.docker"
      - "--entrypoints.web.address=:8085"
    ports:
      - "8085:8085"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - replace-backend
      - replace-frontend
