version: '3.8'
services:
  replace-backend:
    image: ${REPLACE_ECR_BACKEND}:latest
    environment:
      - "REPLACE_DATABASE_URL=${REPLACE_DATABASE_URL}"
      - "REPLACE_DATABASE_USER=${REPLACE_DATABASE_USER}"
      - "REPLACE_DATABASE_PASSWORD=${REPLACE_DATABASE_PASSWORD}"
    expose:
      - 8080
    labels:
      - "traefik.http.routers.backend.rule=(Host(`omicron`) && PathPrefix(`/api`))"
      - "traefik.http.routers.backend.entrypoints=web"

  replace-frontend:
    image: ${REPLACE_ECR_FRONTEND}:latest
    expose:
      - 8080
    labels:
      - "traefik.http.routers.frontend.rule=(Host(`omicron`) && PathPrefix(`/`))"
      - "traefik.http.routers.frontend.entrypoints=web"

  proxy:
    image: traefik:latest
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:8080"
    ports:
      - "80:8080"
#      - "8080:8080" // Uncomment this line to access the Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - replace-backend
      - replace-frontend
