[versions]
kotlin = "1.8.0-Beta"

[libraries]
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
guice = "com.google.inject:guice:5.1.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
node = { id = "com.github.node-gradle.node", version = "3.5.0" }
spring-boot = { id = "org.springframework.boot", version = "3.0.0-SNAPSHOT" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.0" }

