[versions]
kotlin = "1.7.21"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
openapi = { id = "org.openapi.generator", version = "6.2.1" }
spring-boot = { id = "org.springframework.boot", version = "3.0.0-SNAPSHOT" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.0" }

