/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookableEntityDto } from './bookableEntityDto';
import { UserDto } from './userDto';


export interface BookingDto { 
    id?: string;
    userId?: string;
    user?: UserDto;
    bookedEntities?: Array<BookableEntityDto>;
    start?: string;
    end?: string;
}

