/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FloorDto } from './floorDto';
import { BookableEntityTypeDto } from './bookableEntityTypeDto';


export interface BookableEntityDto { 
    id?: string;
    name?: string;
    posX?: number;
    posY?: number;
    floorId?: string;
    parentId?: string;
    typeId?: string;
    floor?: FloorDto;
    parent?: BookableEntityDto;
    type?: BookableEntityTypeDto;
}

