/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnEntityIDString } from './columnEntityIDString';
import { ColumnString } from './columnString';
import { ForeignKeyConstraint } from './foreignKeyConstraint';
import { ColumnInteger } from './columnInteger';
import { ColumnObject } from './columnObject';
import { PrimaryKey } from './primaryKey';
import { ColumnSet } from './columnSet';
import { Index } from './index';


export interface BookableEntities { 
    tableName?: string;
    primaryKey?: PrimaryKey;
    id?: ColumnEntityIDString;
    name?: ColumnString;
    floor_id?: ColumnEntityIDString;
    parent_id?: ColumnEntityIDString;
    pos_x?: ColumnInteger;
    pos_y?: ColumnInteger;
    type_id?: ColumnEntityIDString;
    autoIncColumn?: ColumnObject;
    foreignKeys?: Array<ForeignKeyConstraint>;
    indices?: Array<Index>;
    ddl?: Array<string>;
    columns?: Array<ColumnObject>;
    customPKNameDefined$exposed_core?: boolean;
    tableNameWithoutScheme$exposed_core?: string;
    tableNameWithoutSchemeSanitized$exposed_core?: string;
    fields?: Array<object>;
    source?: ColumnSet;
    realFields?: Array<object>;
}

