/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IColumnType } from './iColumnType';
import { Table } from './table';
import { ForeignKeyConstraint } from './foreignKeyConstraint';
import { ColumnObject } from './columnObject';


export interface ColumnString { 
    table?: Table;
    name?: string;
    columnType?: IColumnType;
    foreignKey?: ForeignKeyConstraint;
    defaultValueFun?: object;
    oneColumnPK$exposed_core?: boolean;
    ddl?: Array<string>;
    referee?: ColumnObject;
    dbDefaultValue$exposed_core?: object;
    primaryConstraintWillBeDefined$exposed_core?: boolean;
}

