/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatabaseDialect } from './databaseDialect';
import { IdentifierManagerApi } from './identifierManagerApi';
import { DatabaseConfig } from './databaseConfig';


export interface Database { 
    config?: DatabaseConfig;
    connector?: object;
    useNestedTransactions?: boolean;
    defaultFetchSize?: number;
    version?: number;
    url?: string;
    vendor?: string;
    dialect?: DatabaseDialect;
    identifierManager?: IdentifierManagerApi;
    supportsAlterTableWithAddColumn?: boolean;
    supportsMultipleResultSets?: boolean;
}

