/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionProvider } from './functionProvider';


export interface DatabaseDialect { 
    name?: string;
    schema?: string;
    database?: string;
    functionProvider?: FunctionProvider;
    dataTypeProvider?: object;
    supportsIfNotExists?: boolean;
    supportsCreateSequence?: boolean;
    needsSequenceToAutoInc?: boolean;
    defaultReferenceOption?: DatabaseDialect.DefaultReferenceOptionEnum;
    supportsCreateSchema?: boolean;
    supportsSubqueryUnions?: boolean;
    likePatternSpecialChars?: { [key: string]: string; };
    needsQuotesWhenSymbolsInNames?: boolean;
    supportsMultipleGeneratedKeys?: boolean;
    supportsOnlyIdentifiersInGeneratedKeys?: boolean;
    supportsSequenceAsGeneratedKeys?: boolean;
    supportsDualTableConcept?: boolean;
    supportsOrderByNullsFirstLast?: boolean;
}
export namespace DatabaseDialect {
    export type DefaultReferenceOptionEnum = 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION';
    export const DefaultReferenceOptionEnum = {
        Cascade: 'CASCADE' as DefaultReferenceOptionEnum,
        SetNull: 'SET NULL' as DefaultReferenceOptionEnum,
        Restrict: 'RESTRICT' as DefaultReferenceOptionEnum,
        NoAction: 'NO ACTION' as DefaultReferenceOptionEnum
    };
}


