/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Schema } from './schema';
import { DatabaseDialect } from './databaseDialect';


export interface DatabaseConfig { 
    sqlLogger?: object;
    useNestedTransactions?: boolean;
    defaultFetchSize?: number;
    defaultIsolationLevel?: number;
    defaultRepetitionAttempts?: number;
    defaultReadOnly?: boolean;
    warnLongQueriesDuration?: number;
    maxEntitiesToStoreInCachePerEntity?: number;
    keepLoadedReferencesOutOfTransaction?: boolean;
    explicitDialect?: DatabaseDialect;
    defaultSchema?: Schema;
    logTooMuchResultSetsThreshold?: number;
}

