/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Query } from './query';
import { IdTableString } from './idTableString';
import { ColumnObject } from './columnObject';
import { ColumnSet } from './columnSet';


export interface EntityClassStringEntityString { 
    table?: IdTableString;
    dependsOnColumns?: Array<ColumnObject>;
    dependsOnTables?: ColumnSet;
    forUpdateStatus?: Query;
}

