/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdTableString } from './idTableString';


export interface EntityIDString { 
    table?: IdTableString;
    get_value?: object;
    value?: string;
}

