/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2022.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileUploadDto } from './fileUploadDto';

export interface FloorDto { 
    id?: string;
    name?: string;
    siteId?: string;
    planFile?: FileUploadDto;
}

