/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResultRow } from './resultRow';
import { Site } from './site';
import { Database } from './database';
import { EntityIDString } from './entityIDString';
import { EntityClassStringEntityString } from './entityClassStringEntityString';


export interface Floor { 
    id?: EntityIDString;
    writeValues?: { [key: string]: object; };
    get_readValues?: ResultRow;
    name?: string;
    siteId?: EntityIDString;
    site?: Site;
    planFileId?: EntityIDString;
    planFile?: any;
    bookableEntities?: object;
    klass?: EntityClassStringEntityString;
    db?: Database;
    klass$exposed_dao?: EntityClassStringEntityString;
    db$exposed_dao?: Database;
    readValues?: ResultRow;
    newEntity$exposed_dao?: boolean;
}

