/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Table } from './table';
import { ColumnObject } from './columnObject';


export interface ForeignKeyConstraint { 
    references?: { [key: string]: ColumnObject; };
    target?: Set<ColumnObject>;
    targetTable?: Table;
    from?: Set<ColumnObject>;
    fromTable?: Table;
    fkName?: string;
    targetTableName?: string;
    fromTableName?: string;
    updateRule?: ForeignKeyConstraint.UpdateRuleEnum;
    deleteRule?: ForeignKeyConstraint.DeleteRuleEnum;
    customFkName?: string;
    foreignKeyPart$exposed_core?: string;
}
export namespace ForeignKeyConstraint {
    export type UpdateRuleEnum = 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION';
    export const UpdateRuleEnum = {
        Cascade: 'CASCADE' as UpdateRuleEnum,
        SetNull: 'SET NULL' as UpdateRuleEnum,
        Restrict: 'RESTRICT' as UpdateRuleEnum,
        NoAction: 'NO ACTION' as UpdateRuleEnum
    };
    export type DeleteRuleEnum = 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION';
    export const DeleteRuleEnum = {
        Cascade: 'CASCADE' as DeleteRuleEnum,
        SetNull: 'SET NULL' as DeleteRuleEnum,
        Restrict: 'RESTRICT' as DeleteRuleEnum,
        NoAction: 'NO ACTION' as DeleteRuleEnum
    };
}


