/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PairExpressionObjectSortOrder { 
    first?: object;
    second?: PairExpressionObjectSortOrder.SecondEnum;
}
export namespace PairExpressionObjectSortOrder {
    export type SecondEnum = 'ASC' | 'DESC' | 'ASC_NULLS_FIRST' | 'DESC_NULLS_FIRST' | 'ASC_NULLS_LAST' | 'DESC_NULLS_LAST';
    export const SecondEnum = {
        Asc: 'ASC' as SecondEnum,
        Desc: 'DESC' as SecondEnum,
        AscNullsFirst: 'ASC_NULLS_FIRST' as SecondEnum,
        DescNullsFirst: 'DESC_NULLS_FIRST' as SecondEnum,
        AscNullsLast: 'ASC_NULLS_LAST' as SecondEnum,
        DescNullsLast: 'DESC_NULLS_LAST' as SecondEnum
    };
}


