/**
 * Replace API
 * API for the Replace application
 *
 * The version of the OpenAPI document: 2023.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldSet } from './fieldSet';
import { Table } from './table';
import { PairExpressionObjectSortOrder } from './pairExpressionObjectSortOrder';


export interface Query { 
    type?: Query.TypeEnum;
    targets?: Array<Table>;
    orderByExpressions?: Array<PairExpressionObjectSortOrder>;
    limit?: number;
    offset?: number;
    fetchSize?: number;
    count?: boolean;
    set?: FieldSet;
    distinct?: boolean;
    groupedByColumns?: Array<object>;
    having?: object;
    forUpdate?: boolean;
    where?: object;
    alwaysBatch?: boolean;
}
export namespace Query {
    export type TypeEnum = 'INSERT' | 'UPDATE' | 'DELETE' | 'SELECT' | 'CREATE' | 'ALTER' | 'TRUNCATE' | 'DROP' | 'GRANT' | 'EXEC' | 'OTHER';
    export const TypeEnum = {
        Insert: 'INSERT' as TypeEnum,
        Update: 'UPDATE' as TypeEnum,
        Delete: 'DELETE' as TypeEnum,
        Select: 'SELECT' as TypeEnum,
        Create: 'CREATE' as TypeEnum,
        Alter: 'ALTER' as TypeEnum,
        Truncate: 'TRUNCATE' as TypeEnum,
        Drop: 'DROP' as TypeEnum,
        Grant: 'GRANT' as TypeEnum,
        Exec: 'EXEC' as TypeEnum,
        Other: 'OTHER' as TypeEnum
    };
}


