name: ktlint-check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev-*
jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew ktlintCheck --continue
